<?php

return [
    // ── Frontend ──────────────────────────────────────────────
    'html'          => ['Frontend',  'devicon-html5-plain colored'],
    'html5'         => ['Frontend',  'devicon-html5-plain colored'],
    'css'           => ['Frontend',  'devicon-css3-plain colored'],
    'css3'          => ['Frontend',  'devicon-css3-plain colored'],
    'javascript'    => ['Frontend',  'devicon-javascript-plain colored'],
    'js'            => ['Frontend',  'devicon-javascript-plain colored'],
    'typescript'    => ['Frontend',  'devicon-typescript-plain colored'],
    'ts'            => ['Frontend',  'devicon-typescript-plain colored'],
    'tailwind'      => ['Frontend',  'devicon-tailwindcss-plain colored'],
    'tailwindcss'   => ['Frontend',  'devicon-tailwindcss-plain colored'],
    'bootstrap'     => ['Frontend',  'devicon-bootstrap-plain colored'],
    'react'         => ['Frontend',  'devicon-react-original colored'],
    'vue'           => ['Frontend',  'devicon-vuejs-plain colored'],
    'vuejs'         => ['Frontend',  'devicon-vuejs-plain colored'],
    'angular'       => ['Frontend',  'devicon-angularjs-plain colored'],
    'sass'          => ['Frontend',  'devicon-sass-original colored'],
    'scss'          => ['Frontend',  'devicon-sass-original colored'],
    'jquery'        => ['Frontend',  'devicon-jquery-plain colored'],
    'nextjs'        => ['Frontend',  'devicon-nextjs-original colored'],
    'next.js'       => ['Frontend',  'devicon-nextjs-original colored'],
    'nuxtjs'        => ['Frontend',  'devicon-nuxtjs-plain colored'],
    'svelte'        => ['Frontend',  'devicon-svelte-plain colored'],
    'alpinejs'      => ['Frontend',  'devicon-alpinejs-original colored'],

    // ── Backend ───────────────────────────────────────────────
    'php'           => ['Backend',   'devicon-php-plain colored'],
    'laravel'       => ['Backend',   'devicon-laravel-plain colored'],
    'nodejs'        => ['Backend',   'devicon-nodejs-plain colored'],
    'node'          => ['Backend',   'devicon-nodejs-plain colored'],
    'node.js'       => ['Backend',   'devicon-nodejs-plain colored'],
    'express'       => ['Backend',   'devicon-express-original colored'],
    'python'        => ['Backend',   'devicon-python-plain colored'],
    'django'        => ['Backend',   'devicon-django-plain colored'],
    'flask'         => ['Backend',   'devicon-flask-original colored'],
    'java'          => ['Backend',   'devicon-java-plain colored'],
    'spring'        => ['Backend',   'devicon-spring-plain colored'],
    'csharp'        => ['Backend',   'devicon-csharp-plain colored'],
    'c#'            => ['Backend',   'devicon-csharp-plain colored'],
    'dotnet'        => ['Backend',   'devicon-dot-net-plain colored'],
    '.net'          => ['Backend',   'devicon-dot-net-plain colored'],
    'ruby'          => ['Backend',   'devicon-ruby-plain colored'],
    'rails'         => ['Backend',   'devicon-rails-plain colored'],
    'go'            => ['Backend',   'devicon-go-plain colored'],
    'golang'        => ['Backend',   'devicon-go-plain colored'],
    'rust'          => ['Backend',   'devicon-rust-plain colored'],
    'kotlin'        => ['Backend',   'devicon-kotlin-plain colored'],

    // ── Database ──────────────────────────────────────────────
    'mysql'         => ['Database',  'devicon-mysql-plain colored'],
    'postgresql'    => ['Database',  'devicon-postgresql-plain colored'],
    'postgres'      => ['Database',  'devicon-postgresql-plain colored'],
    'mongodb'       => ['Database',  'devicon-mongodb-plain colored'],
    'mongo'         => ['Database',  'devicon-mongodb-plain colored'],
    'sqlite'        => ['Database',  'devicon-sqlite-plain colored'],
    'redis'         => ['Database',  'devicon-redis-plain colored'],
    'firebase'      => ['Database',  'devicon-firebase-plain colored'],
    'supabase'      => ['Database',  'devicon-supabase-plain colored'],

    // ── Mobile ────────────────────────────────────────────────
    'swift'         => ['Mobile',    'devicon-swift-plain colored'],
    'flutter'       => ['Mobile',    'devicon-flutter-plain colored'],
    'dart'          => ['Mobile',    'devicon-dart-plain colored'],
    'reactnative'   => ['Mobile',    'devicon-react-original colored'],
    'react native'  => ['Mobile',    'devicon-react-original colored'],

    // ── DevOps ────────────────────────────────────────────────
    'git'           => ['DevOps',    'devicon-git-plain colored'],
    'github'        => ['DevOps',    'devicon-github-original colored'],
    'docker'        => ['DevOps',    'devicon-docker-plain colored'],
    'kubernetes'    => ['DevOps',    'devicon-kubernetes-plain colored'],
    'nginx'         => ['DevOps',    'devicon-nginx-original colored'],
    'linux'         => ['DevOps',    'devicon-linux-plain colored'],
    'bash'          => ['DevOps',    'devicon-bash-plain colored'],
    'aws'           => ['DevOps',    'devicon-amazonwebservices-original colored'],
    'azure'         => ['DevOps',    'devicon-azure-plain colored'],
];
